GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID


lrCost				   = false
transportationCost     = false
ddmCost 			   = false
bookingCommissionCost  = false
deliveryCommissionCost = false
insertLrCostWithZero   = false
companyCommissionCost  = false