##	Vehicle Wise LHPV Account Report Default Properties
## 1 = true , 2 = false 
lhpvViewTbl_SRNO 				=	1
lhpvViewTbl_DATE				=	1
lhpvViewTbl_VEHICLENO			=	1
lhpvViewTbl_LHPVNO				=	1
lhpvViewTbl_FROM				=	1
lhpvViewTbl_BLHPVNO				=	1
lhpvViewTbl_BLHPVBRANCH			=	1
lhpvViewTbl_TOPAY				=	1
lhpvViewTbl_PAID				=	1
lhpvViewTbl_TBB					=	1
lhpvViewTbl_TOTAL				=	1
lhpvViewTbl_TRUCKHIRE			=	1
lhpvViewTbl_ADVANCE				=	1
lhpvViewTbl_BALANCE				=	1
lhpvViewTbl_BASICFREIGHT		=	1
lhpvViewTbl_PL					=	2

##	Vehicle Wise LHPV Account Report Group wise Properties
lhpvViewTbl_SRNO_226 			=	1
lhpvViewTbl_FROM_226			=	1

lhpvViewTbl_BASICFREIGHT_226	=	2