GroupName	= Konduskar S R Travels
GroupCode	= srk
GroupId		= 54

changeLabelSourceSubRegionToFromCity		= true
changeLabelSourceBranchToFromBranch			= true
changeLabelDestinationSubRegionToToCity		= true
changeLabelDestinationBranchToToBranch		= true