GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

changeLabelSourceSubRegionToFromCity		= false
changeLabelSourceBranchToFromBranch			= false
changeLabelDestinationSubRegionToToCity		= false
changeLabelDestinationBranchToToBranch		= false
isShowGroupMergingBranchData				= false
showRegionLabel								= false
showSubRegionBranchAndDestinationSubRegionFiled = false
hideDeactivatedSubregion					= false
isShowWithoutMergingGroupBranchData			= false
allowTimeLocking							= false
startHour									= 17
endHour										= 21
serverIdentifiersForTimeLocking				= 2
allowBranchConsolidatorTimeLocking			= true