GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

BookingBranchSummaryReport			= false
BookingRegionWiseSummaryReport		= false
BookingSummaryDestinationWise 		= false
BookingSummaryReport				= false
BookingRegisterReport				= false
BookButNotDispatchReport			= false
FtlCollectionReport					= false
LsBookingRegisterReport				= false
LsWithoutLhpvReport					= false
DlyTypeWiseGodownStockReport		= false
DateWiseGodownStockReport			= false
DlyStmtCashChequeReport				= false
DlyStmtCashChequeDetailReport		= false
GodownStockReport					= false
TURRegisterReport					= false
DoorDeliveryMemoRegister			= false
showHamaliChargeColumn				= false
showDoorDeliveryChargeColumn		= false