#LS CONFIG PROPERTY
GroupName	= Kalpana Cargo
GroupCode	= kcpl
GroupId		= 3

CrossingSubregionBranchAllowForCargo			= true
vehicleNumberValidate   						= true
showAstrikForEwayBillLrs						= true
allowAutoGenerateConEWaybill					= true
showSeparateCrossingDataInLsPrint				= true
cargoOldFlowLSPrint								= true
showPrivateMark									= true