#LS CONFIG PROPERTY
GroupName	= Royal carrier & Courier Pvt. Ltd.
GroupCode	= RCC
GroupId		= 46

AllowSortingToDispatchSearchListPopup	= true
AllowSortingByColumn					= 1
AllowSortingInOrder						= DESC
cargoOldFlowLSPrint				= true
