#LS CONFIG PROPERTY
GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_ID

LicenseNo			  = false
LicenseNoAutoComplete = false
Weighbridge			  = false
AgentCrossingTruckNoValidation = true
CrossingSubregionBranchAllowForCargo		= false
CrossingSubregionBranchAllowForTransCargo	= false
NewBranchCrossingMapAllow					= false
AllowAllOptionInDestinationList		= false
ShowManualLS				= false
RangeCheckInManualLS			= true
driverMobileNumber			= false
driverMobileNumberValidation		= false
cleanerName				= true
cleanerNameValidation			= true
AllowSortingToDispatchSearchListPopup	= false

#	1 for Booking Date, 2 for WayBill Number, 3 for Source Branch,
#	4 Destination Branch, 5 Source Subregion, 6 Destination Subregion,
#	9 Consignor Name, 10 Consignee Name


AllowSortingByColumn					= 0	
AllowSortingInOrder						= ASC
IsCrossingRateAllow						= false
IsLoadingHamaliRateAllow				= true
IsUnLoadingHamaliRateAllow				= true
IsCrossingHireRateAllow					= true
OnlyCrossingHireAmountApplicable		= false
CrossingAgentWiseDestinationPopulate	= false
applyRatesAfterAddToDispatch = true
applyCrossingRateOnLRSearch				= false
applyCrossingHireRateOnActualWeight		= false
showCredtDebitInfo = false
isDoorDeliveryRateAllow					= false
isManualLsDateValidationCheck			= true
vehicleNumberValidate   = false
isEditDoorDeliveryAllow				= false
typeOfEditCrossingHireAllow		= 1,3
isManualLSDateRequiredInReceiveDel	= false
showBkgDateOnDispatch   = false
srcDestWiseSeqCounter				= false
cargoOldFlowLSPrint							= false
transportOldFlowLSPrint						= false
validateSelectionForSingleLR				= false
IsTripHisabRequired							= false
displayCrossingMemoConfigurationDataUpdatePanel	= true
validateRemark				= false
editcrossinghirecolumnshow	= false
isChargedWeightShow			= false
showAstrikForEwayBillLrs						= false
allowAutoGenerateConEWaybill					= false
TransportModeForSearch							= false
AllowScrapSeqCounter					= false
allowAppendSingleLrDitect 	= false
hideDeactivatedSubregion	= false
tokenWiseCheckingForDuplicateTransaction		= true
isGroupWiseLSSequenceCounter		= false
showSeparateCrossingDataInLsPrint				= false
fuelHisabModuleAllowed				= false
showConsignorNameAndNoOfArticles	= false
showHamaliColumn					= false
editCrossingAgentNameOnDeliveryType				= false
showPrivateMark						= false