/**
 * @Author	Anant Chaudhary	13-10-2015
 */

var SETTLE_WITH_EXCESS	= 1;
var SETTLE_WITH_CLAIM	= 2;
var SETTLE_WITH_NOCLAIM	= 3;

var SETTLE_WITH_SHORT	= 1;
var SETTLE_WITH_FOCLR	= 2;
var SETTLE_WITH_UGD		= 3;

var SHORT_SETTLED					= 4;
var DAMAGE_SETTLED					= 5;
var SHORT_SETTLED_DAMAGE_UNSETTLED	= 6;
var SHORT_UNSETTLED_DAMAGE_SETTLED	= 7;
var BOTH_SETTLED					= 8;
