GroupName	= Defauts for Travels
GroupCode	= default
GroupId		= 0
#consignorPanel Type 1 for name,2 for mobile no.
#if partyPanelType = 2 make ConsigneePhnAutocomplete true
partyPanelType					= 1
### Create WayBill Configuration
WayBillType						= true
BookingType						= false
DeliveryDestination				= true
#0 for Without Subregion
#1 for With Subregion
FrightuptoDestination			= false
VehicleType						= false
Consignor						= true
Consignee						= true
AddArticle						= true
WaightAndAmount					= true
ChargeType						= true
# default charge type
# 1 WEIGHT, 2 FIX, 3 QUANTITY, 4 CUBIC_RATE
DefaultChargeType				= 3
Qty								= true
# Article type or type of packing
ArticleType						= true
SaidToContain					= true
QtyAmt							= true
AddButton						= true
ActualWght						= true
ChargedWght						= true
WghtRate						= true
WghtAmt							= true
FixAmt							= false
STPaidBy						= true
DefaultSTPaidBy					= 0
InvoiceNo						= true
DeclaredValue					= true
DeliveryAt						= true
#  DefaultDeliveryAt : 1:Godown, 2-Door, 3-DDDV , 4-Truck Delivery
DefaultDeliveryAt				= 1
Remark							= false
DefaultPaymentType				= 1
PaymentType						= true
PaymentTypeCheque				= true
CollectionPerson				= false
ConsignorBillingPartyName		= true
TotalQuantity					= true
SaveButton						= true
WayBillCharges					= true
Taxes							= true
Discount						= false

DiscountTypes					= true
CommodityType					= false

# Overlay
AddNewPartyOverlay				= false
SaidToContainOverlay			= false

DefaultWayBillType				= F7
MinWeight						= 0
MaxWeight						= 0

ShowTruckTypeOnDDDV				= false

LRCharge						= 0.0

# to allow charged weight more the truck capacity
FTLWeightAllowMoreThenTruck		= false

# booking charges value with decimal or rounded
BookingChargesFloatValueAllowed	= true



# Form Validation
DestinationValidate				= true
FreightUptoValidate				= false
ConsignorMobileNoValidate		= true
ConsigneeMobileNoValidate		= true
BillingPartyValidate			= true
VehicleTypeValidate				= false
LRChargeValidate				= false
Form_403_402Validate			= false
InvoiceNoValidate				= false
STPaidByValidate				= true
RemarkValidate					= false
FormsValidate					= false
DeclaredValueValidate			= false
WeightValidate					= false
SaidToContainValidate			= false

WeightValidateFlover			= 1
DeclaredValueFlavorType			= 1
# Declared Value Validation flavor
GeneralValidate					= 1
ValidateOnInvoiceNo				= 2

# 0-Disabled (No checking), 1- Required, 2-Valid Mobile No required
ConsignorMobileNumberValidationFlavor	= 0
ConsigneeMobileNumberValidationFlavor	= 0

# weight and quantity amount calculation flavor.
# if booking type sundry = 2, general calculation = 1
QtyFlavor						= 1


# 1 quantityamount. 2 quantity * quantityamount
ConsignmentDetailsAmountCalculationFlavor			= 1
# 1 set 0static 2 set dynamic.
ConsignmentDetailsArtoicleTypeMasterIdFlavor		= 1
ConsignmentDetailsArtoicleTypeMasterId				= 1

# New Rate Master Panel Display
applyRateAuto					= true

#Charges to apply Rates
ApplyRateForCharges				= 1,24

# Autocomplete response if no record found in database.  1 for No record found , 2 for same typed data = 2
BookingConsigneeNameAutocompleteResponse			= 2
BookingConsignorNameAutocompleteResponse			= 2
BookingConsigneePhnAutocompleteResponse				= 2
BookingDestinationutocompleteResponse				= 1
BookingFreightUptoBranchAutocompleteResponse		= 1
BookingSaidToContainAutocompleteResponse			= 2
BookingBillingPartyNameAutocompleteResponse			= 1
BookingSearchCollectionPersonAutocompleteResponse	= 1

ConsigneeNameAutocomplete				= true
ConsignorNameAutocomplete				= true
DestinationAutocomplete					= true
FreightUptoBranchAutocomplete			= false
SaidToContainAutocomplete				= true
BillingPartyNameAutocomplete			= true
SearchCollectionPersonAutocomplete		= true
ConsignorPhnAutocomplete				= false

#if partyPanelType = 2 make true
ConsigneePhnAutocomplete				= false

#LS WeighCharge


# WaybillCancellation

#Minimum Quantity Amount
MinimumQuantityAmount					= 10
QuantityAmountCharges					= 0
QuantityAmountConfigFlavor				= 1
MinQtyAmtTobeAssigned					= 0
#To allow Freight charge mandatory
freightChargeMandatory			= false


#Branch code wise waybill number generation
ShowCityAndDestinationBranch			= false
AllowAjaxCheckOnDestinationBranchSelect = false
AllowDuplicatePartySave					= false


ShowAccountGroupInBranchAutoCompleteOnBookingPage	= false

#Allow some charge to be displayed on specific type of LR 
AllowSpecificChargeShow					= false
#waybill type underscore charge id
WayBillTypeChargeIdToShowCharge			= 0_0


DefaultFormType					= 1018
FormTypeIds						= 1018

gstnNumber									= true
savePartyAfterGstNumber						= true
updatePartyGstNumber						= true