GroupName	= Mahasagar Transport
GroupCode	= MTL
GroupId		= 9

Branch_Wise = false

BranchId_GroupName = 13890_Mahasagar Logistics,13881_Mahasagar Logistics,13922_Mahasagar Logistics,13923_Mahasagar Logistics,13919_Mahasagar Logistics