# here we are setting key value for for cash statement report configuration
# by using this key value pair we are generating cash statement report 
#For setting permission
CASH_STATEMENT								= false
IS_ALLOW_TXNCHECKER_ENTRY	 				= false
