# here we are setting key value for for cash statement report configuration
# by using this key value pair we are generating cash statement report 
#For setting permission
CASH_STATEMENT								= true
IS_ALLOW_TXNCHECKER_ENTRY	 				= true

#IN cashstatementConfig.json  isCustomDeliveryChargeWiseEntry
CUSTOM_DELIVERY_CHARGES_SEPERATE_ENTRY		= false

MANUAL_TRANSACTION_CHECK_IN_CURRENT_DATE	= false
DDM_SETTLEMENT_SEPERATE_ENTRY				= false
STBS_SETTLEMENT_SEPERATE_ENTRY				= false
BLHPV_CHARGES_WISE_ENTRY					= false
LS_Receive									= false
LR_COUNT_REQUIRED				  			= false
BookingCommissionDebitEffect				= false
DeliveryCommissionDebitEffect				= false	
BookingCommissionCancelDebitEffect			= false
DeliveryCommissionCancelDebitEffect			= false
IS_ALLOW_CROSSING_AGENT_COMMISSION_ENTRY	= false
IS_ALLOW_SHORT_CREDIT_PAYMENT_SEPERATE_ENTRY= false
IS_ALLOW_CREDIT_PAYMENT_DISCOUNT			= true
isAllowDispatchCreditEntryForTopayLr		= false
isAllowDebitEntryForTopayLRAfterLsCancellation		= false
isAllowDispatchEditDestEntry						= false
isAllowDebitEntryAfterEditLs						= false
isAllowSingleEntryForFundTransfer					= false
isAllowSingleEntryForFundReceive					= false
isAllowSingleEntryForBranchIncome					= false
isHeadWiseExpenseEntryNeeded						= false
isAllowSingleEntryForLhpvAdvance					= false
isAllowSingleEntryForBlhpv							= false

#For Setting Labels
Paid										= Paid Bhada
CancelPaid									= Cancel Paid Bhada
Bill_Payment								= TBB
Short_Credit_Payment						= STB
BLHPV_Payment								= Lorry Hire
Fund_Transfer								= Cash Transfer To
Fund_Receive								= Cash Receive From
Office_Income								= Office Income
Octroi_Payment								= Octroi Payment
Crossing_Agent_Payment						= Crossing Agent Payment
LHPV_Advance_Payment_Voucher				= LHPV Advance Payment
LHPV_Additional_Advance_Payment_Voucher		= LHPV Additional Advance Payment
Delivery_Payment							= Cash Delivery A/C
Cancel_Delivery 							= Delivery Cancel
DDM_Payment									= DDM Payment
Office_Expense								= Office Expense
CANCEL_OFFICE_INCOME						= Cancel Office Income
TOPAY_PAID_CHARGES							= To Pay Paid Charges
LS_Receive_Label							= Towards Freight Collection
CANCEL_OFFICE_EXPENCE						= Cancel Office Expense
#For Setting Labels
BLHPV_CANCELLATION_LABEL 					= Cancel BLHPV
DDCHARGE_DEBIT_LABEL						= DD Charge
DATA_FOR_LOADING_CHARGE_LABEL 				= Loading Charge
DDM_SETTLEMENT_LABEL						= Delivery Collection
BLHPV_SHORT_CREDIT_PAYMENT 					= BLHPV Short Credit Payment
EDIT_LR_RATE			   					= EDIT LR 
EDIT_CONSIGNMENT			   				= EDIT CONSIGNMENT 
ShowGroupMergingBranchData					= false
isAllowTdsDebitEntry						= false
ACCOUNT_HEADER_TDS_RECEIVABLES				= TDS Receivables
UNLOADING_HAMALI_LABEL						= Unloading Hamali
UNLOADING_HAMALI_CANCEL_LABEL				= Cancel - Unloading Hamali

isDisplayRowForTdsDetailInReport			= false
isDisplayNarration 							= false
IS_ALLOW_SHORT_CREDIT_PAYMENT_SEPERATE_ENTRY	= false
IS_ALLOW_PAID_BHADA_SEPERATE_ENTRY			= false
IS_ALLOW_DELIVERY_COLLECTION_SEPERATE_ENTRY	= false

AGENT_BILL_SETTLEMENT						= Agent Branch Bill Payment

TOPAY_LR_PAYMENT							= Topay Delivery
LS_CANCELLATION								= LS Cancellation
EDIT_LS_DEST								= Edit LS Destination
EDIT_LS_REMOVE_LR							= Edit LS 
GENERATE_CR_LABEL							= Delivery Collection
showBillPaymentTdsClubAmount				= true

ACCOUNT_HEADER_CLAIM_ENTRY					= Claim Entry
ACCOUNT_HEADER_DEDUCTION_ENTRY				= Deduction Entry
isAllowClaimDebitEntry						= false
isAllowDeductionDebitEntry					= false
isDisplayRowForClaimEntryInReport			= false
isDisplayRowForDeductionEntryInReport		= false
isShowDdmWiseDiscountEntry					= false
isShowStbsWiseDiscountEntry					= false
isShowLsWiseEntryForRecAndDly				= false
isShowLsWiseDeliveryChargesSeperateEntry	= false
bookingCommissionDebitAllowedForPaidWayBill	= false
isShowSingleEntryForCashlessTransactions	= false
isShowTdsEntryOnlyForCashWithRemark			= false
isShowDdmLorryHireEntryWithRemark			= false
isShowReverseBlhpvEntry						= false

operationalBranchEntryForPaidLr				= false
isAllowOnlyDebitEntryForCashlessPaymentInFundTransfer	= false
isAllowOnlyCreditEntryForCashlessPaymentInFundReceive	= false
showClubEntryForMultipleBillClearance		= false

isShowSeparateEntryForNegotiatedPayment		= true
ACCOUNT_HEADER_NEGOTIATED_ENTRY				= Negotiated Entry
doNotAllowCashStatementEntryForAgentbranch	= false
allowUnloadingHamaliEntry					= false
EDIT_LS_APPEND_LR							= Edit LS - Append LR
showClubEntryForMultipleShortCreditPayment	= false

# To Tally Credit And Debit Records In CashLess Transactions With TDS, Claim, Etc. If Credit = 1000 and TDS = 200, then Debit has 2 rows(800 + 200)
showSeparateRecordsForCashlessTransactions	= false

showDeliveryDiscountInShortCreditPayment	= false
CANCEL_CROSSING_AGENT_CR					= Crossing Agent Cr Cancel
showLrNumberInRemarkColumn					= false
showTotalAmountWithoutTdsAndShowTdsNarration= false
showSingleEntryForTdsInCashessTransactions	= false
showSeperateEntryForDiscountInCashessTransactions	= false
BOOKING_COMMISSION_LABEL					= Booking Commission
CANCEL_BOOKING_COMMISSION_LABEL				= Cancel Booking Commission
isAllowDeliveryTimeUnloadingEntry			= false