DeliverySequenceCounter					= true
GroupLevelDeliverySequenceCounter		= false
DeliveryReceivedAmountAllowed			= false
DeliveryCreditorAutocomplete			= true
SearchCollectionPersonAutocomplete		= false
DeliveredToNameAutoComplete				= false
ConsineeNameAutoComplete				= false
DisplayConsineeNameField				= false
OctroiServiceCalculationFilter			= 1
OctroiDeliveryCalculationFilter			= 1
OctroiFormMinimumAmount					= 0
DeliveredToNameValidate					= true
DeliveredToPhoneNumberValidate			= true
DeliverySTPaidByValidate				= false
DeliveryRemarkValidate					= false
OctroiValidate							= false
DeliveryReceivedAmountValidate			= false
DeliverySearchCollectionPersontValidate	= false
DeliveryCreditorValidate				= false
DeliveryManualCRNumbertValidate			= true
DeliverySTPaidBy						= true
DeliveryTimeServiceTax					= true
PhotoServiceValidate					= false
SignatureServiceValidate				= false
PhotoServiceOnDeposit					= false
SignatureServiceOnDeposit				= false
DeliverySTPaidByValidateFlavor			= 1
DeliveryDefaultSTPaidBy					= 0
DeliveryDefaultSTPaidByForPaid			= 1
DeliveryDefaultSTPaidByForToPay			= 2
DeliveryDefaultSTPaidByForTBB			= 1
DeliveryDefaultSTPaidByForFOC			= 0
GenerateCashReciptLinks					= true
GenerateCashReciptView					= true
GenerateCashReciptEdit					= true
GenerateCashReciptPrint					= true
AllowCRPrintOnNoDeliveryCharge			= true
ShowConsigneeDetailsInDeliveryDetails	= false
ApplyDeliveryCharges					= false
GenerateCashReciptPrintFromNewFlow		= false
DefaultPaymentType						= 0
showDeliveryPaymentType					= true
isFreightZeroAllow						= true
excludeDemurrageCalculation				= false
applyRateAuto					= false
wayBillStatusAllowForDemurrageCalculation					= 7,11,15
minimumBookingTotalForDemurrageCalculation					= 0
DisplayReceivablesTypeField				= false
DisplayApprovedByField					= false
ValidateApprovedByField					= false
ReceivableTypeListByOrder				= 1,2,3,4
DefaultReceivableType					= 0
ConsigneeCopy							= false
AgainstLetterHead						= false
AgainstBond								= false
NotApplicable							= false
AllowToDeliverIfManualCRDateEarlierToBookingDate	= false
isIncreaseMobileNoLength	= false
prefixForMobileNumber		= 0 
EditDoorDeliveryAllow			= false
ShowReceivedLrDirectly			= false
showCRNumber					= false
isOldFlowNeeded					= false
displayStatusDetails			= true
displayDispatchDetails			= true
isCRNoGenerationAllow			= true
isWSCRPrintNeeded				= true
isAllowManualCRWithoutSeqCounter 	= false
CalculateFocBillAmountForOctroiCharges		= false
DefaultPanNumber							= false
isChargeAppliedOnBookingTotal				= false
UnloadingChargeId							= 0
BookingTotalAmount							= 0
IsUserDefinedRateAllow						= false
EditDemmurageAmountAllow					= false
STCalOnBookingDeliveyTotalIfNotAllowedAtBookingTime	= false
isPartialPaymentAllow						= false
AllowEditCustomerAfterLrReceiveForAll		= false
SetPartyCodeInDeliverToName					= false
allowBranchWiseCRPrint						= false
branchCodeListForNewCRWSPrintFlow			= 0
disableConsignorOption				= false
disableTransporterOption			= false
disableSTPaidBy						= false
AllowToDeliverLRForSELFConsigneeParty	= true
hideMannualCRSequenceMsg				= false
showAutoCharge							= false
autoChargeIdWithName					= 0
ConsigneePartyAutoSaveAllow				= false
branchIdForNewPrintFromOldFlow			= 0
calculateCustomDemurrage						= false
calculateDemurrageBasedOnSourceSubRegion		= false
sourceSubRegionIdsForDemurrage					= 0
calculateDemurageBasedOnDestinationSubRegion	= false
destinationSubRegionIdsForDemurrage				= 0
calculateDemurageBasedOnPackingType				= false
packingTypeMasterIdsForDemurrage				= 0
customDemurrageOnDays							= false
customDemurrageOnRate							= false
customDemurrageExemptedDays						= 0
customDemurrageApplicableRate					= 0
showReprintButton								= true
gstnNumber										= false
showReprintButton								= true
validateDRCharge								= false
setDefaultDRCharge								= false
setDefaultDRChargeAmount						= 0
calculateDemerageOnCustomDaysWise				= false
multiplyWithChargableDaysInFixAmount			= true
allowPackingGroupWiseDemerageCalculation		= false
packingGroupIdsForDemerageCalculation			= 0
isBlackListPartyCheckingAllow					= false
isPartyDiscountCheckingAllowed					= false
HideBookingChargesPanelAndBookingAmountOnLRType					= false
LRTypeToHideBookingChargesPanelAndBookingAmount					= 0
isDeliveryTimeShortCreditAllowedOnGodownDelivery				= true
WayBillTypeWiseDiscountAmountOnChangeOfConsigneePartyRate		= false
WayBillTypeIdsForDiscountAmountOnChangeOfConsigneePartyRate		= 0
ChargesToAddExtraAmountOnChangeOfConsigneePartyRate				= 0
isAllowAlphnumericWithSpecialCharacters 						= true
specialCharacterFilter	= 2
AllowedSpecialCharacters = 32,38
ReceiveSingleLR								= false
validateShortCreditAllowOnTxnType			= false
isCTODetainAllowed							= false
multiCRPrintNeeded							= true
deliveryQuantityZeroValidation				= false
wayBillTypeWiseCrNoGenerationNeeded			= false
waybillTypeIdsForCrNoGeneration				= 0
branchAbbrvnWiseCrNo						= false
showCRPrintAfterBooking						= true
configDiscount								= false
ReceiverToNameValidate						= false
showReceiverToName							= false
doNotCalculateDemuaarageOnFtlDddvDoorLR		= false
allowConfigDiscountOnDemurrage				= false
showChargesToExecutiveAndGroupAdmin			= false
showGodownStockReportLink					= false
GodownStockReportLink						= GodownStockReport.do?pageId=50&eventId=50
showOnlyManualCrDate						= false
showZeroAmountInCr							= false
centralizedCrCancellation					= false
isAlertOnCashPayment						= false
branchIdsForAlertOnCashPayment				= 0
isOldFlowNeededIfBranchNotFoundForWs 		= false
isValidateDeliveredToNameAndNumberOnBlur	= false
allowDeliveryAfterDDMCreation				= false
applyUnLoadingChargeOnFreightChargeAmt		= false
minimumFreightChargeValueToApplyDeliveryRate	= 0
unloadingChargeRatePerArticle					= 0
wayBillTypeWiseApplyChargeRate					= false
isAllowPopUpForPendingLRs					= false
fetchDataForReceivedLRs						= false
fetchDataForDispatchedLRs					= false
isCalculateCommisssionOnDestBranch			= false
allowShortCreditPaymentForSavedParties					= false
shortCreditConfigLimitAllowed							= false
showDeliveryCharges										= false
showManualCrOptionForUserWise							= false
allowAutoGenerateConEWaybill							= false
showTruckNumberField									= false
disableDeliveryIfPaymentNotReceived			= false
disableShortCreditPaymentMode				= false
shortCreditDeliveryLockingBeforeDays		= 0
completeDeliveryLockingBeforeDays			= 0
billingBranch											= false
loggedInBranchAsBillingBranch							= true
crPdfGenerationAllowed									= false
showCashPaymentTypeGstOnCongisneeAndConsignor			= false
multipleCrPrintForNewFlow					= false
disableSpecificCharges						= false
disableChargeIds							= 0
lrSearchWithOutBranchCode					= false
isAllowSameAsNetCrPrintForNetcWithoutBill 	= false
hideDiscountOnLrTypeTbb                     = false
isCalculateCommisssionOnAgentBranchOrDestBranch	= false
lrTypeForDeliveryCharge					= 0
DeliverytoId							= 0
showDlyChargeOnlyForGodown				= false
deliveryChargeId						= 0
isShowStbsCreationAllowCheckBox			= false
doNotAllowCRPrintForshortCreditPayment	= false
showDemurrageCalculation				= false
AllowToDeliverIfManualCRDateEarlierToReceiveDate = false
doNotShowManualCrBackDate				= false
deliveryRemarkValidateOnDiscount		= false
hideManualCrDateSubRegionWise			= false
SubRegionIdToHideManualCrDate			= 0
singleCrPrintWithMultiLrNeeded			= false
allowOnlyNumericInCharges				= true
isGoodsUndeliveredEntryAllowed			= false
deliveryLock							= false
showClaimAmountField					= false
deliveryChargeCalculatePerArticleByBranchId	= 0
branchIdsForChangeInPerArticleAfterSomeQuantity	= 0
chargeIdForCashStatementInsert			= 0
branchIdForUnloadingCharge				= 0
isShowStbsCreationAllowCheckBoxBySubregionId = 0
allowToChangeDeliveryTo					= false
deliveryhandlingChargePerArticle		= false
quantity_Amount											= 0_0
handlingChargesNotApplicableForPackingTypeIds 			= 0
handlingChargesAmountApplicableForPackingTypeIds	 	= 0
perArticleAmountForPacketPackingType					= 0
perArticleAmountForBikePackingType						= 0
allowToRemoveDefaultUnloadingCharge          = false
doNotAllowToSelectDiscountType             = false
discountTypeIdToNotAllowForSelection       = 0
delivertTimeShowBillSelection              = false
kalpanaCargoUnloadingCalculation		   = false
changeStPaidbyOnPartyGSTN				   = false
isAllowCRCancellationLocking	= false
CRCancelltionAllowedAfterDays	= 0
sourceBranchIdForUnloading						= 0
handlingChargeNotIncrease						=false
allowActualDestBranchId							= false
allowReceiveDateAfterCrCancel					= false
destinationBranchIdForUnloading					= 0
validateDateBeforeDemurrageCalculation			= false
dateForDemurrageCalculation						= 01-09-2023
validateFutureDate								= true
allowShortCreditPaymentTypeOnShortCreditParty	= false