GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID


nameColumnDisplay				= true
addressColumnDisplay			= true
cityNameColumnDisplay			= true
branchNameColumnDisplay			= true
pincodeColumnDisplay			= true
contactPersonColumnDisplay		= true
departmentColumnDisplay			= true
mobileNumberColumnDisplay		= true
phoneNumberColumnDisplay		= true
faxNumberColumnDisplay			= true
emailAddressColumnDisplay		= true
partyTypeColumnDisplay			= true
locationColumnDisplay			= true
accountSubTypeColumnDisplay		= true
mobileNumber2ColumnDisplay		= true
phoneNumber2ColumnDisplay		= true
markettingPersonColumnDisplay	= true
serviceTaxNoColumnDisplay		= true
tinNumberColumnDisplay			= true
panNumberColumnDisplay			= true
isTBBPartyColumnDisplay			= true
isServiceTaxReqColumnDisplay	= true
isBlackListColumnDisplay		= true