# here we are setting key value for for Exception detection for SMS problem 
#if true then it will send Email to developers or support regarding problem

SMS_PROBLEM_SEND_EMAIL=true
SMS_DELIVERY_PROBLEM_SEND_EMAIL = true