GroupName	= Gujarat Cargo
GroupCode	= gtpl
GroupId		= 4

DefaultMinDate								= 01-10-2016

BookingPrintMinDateALlow					= true
BookingPrintMinDate							= 01-10-2016

DispatchMinDateAllow						= true
DispatchMinDate								= 01-10-2016

LoadingSheetMinDateAllow					= true
LoadingSheetMinDate							= 01-10-2016

ManualLoadingSheetMinDateAllow				= true
ManualLoadingSheetMinDate					= 01-10-2016

InterBranchLSMinDateAllow					= true
InterBranchLSMinDate						= 01-10-2016

ReceiveMinDateAllow							= true
ReceiveMinDate								= 01-10-2016

GodownReceiveMinDateAllow					= true
GodownReceiveMinDate						= 01-10-2016

CreateDDMMinDateAllow						= true
CreateDDMMinDate							= 01-10-2016

DDMSettlementMinDateAllow					= true
DDMSettlementMinDate						= 01-10-2016

CreateCreditorInvoiceMinDateAllow			= true
CreateCreditorInvoiceMinDate				= 01-10-2016

CreditorInvoicePaymentMinDateAllow			= true
CreditorInvoicePaymentMinDate				= 01-10-2016

CancelCreditorInvoiceMinDateAllow			= true
CancelCreditorInvoiceMinDate				= 01-10-2016

MultipleInvoicePaymentMinDateAllow			= true
MultipleInvoicePaymentMinDate				= 01-10-2016

LRCreditPaymentMinDateAllow					= true
LRCreditPaymentMinDate						= 01-10-2016

CreditCollectionModuleMinDateAllow			= true
CreditCollectionModuleMinDate				= 01-10-2016

CreditCollectionPaymentModuleMinDateAllow	= true
CreditCollectionPaymentModuleMinDate		= 01-10-2016

LHPVMinDateAllow							= true
LHPVMinDate									= 01-10-2016

BLHPVMinDateAllow							= true
BLHPVMinDate								= 01-10-2016

STBSCreationMinDateAllow					= true
STBSCreationMinDate							= 01-10-2016

STBSSettlementMinDateAllow					= true
STBSSettlementMinDate						= 01-10-2016

GenerateCRMinDateAllow						= true
GenerateCRMinDate							= 01-10-2016

GenerateCRForMultiLRMinDateAllow			= true
GenerateCRForMultiLRMinDate					= 01-10-2016

CancelCRMinDateAllow						= true
CancelCRMinDate								= 01-10-2016

CrossingAgentInvoiceMinDateAllow			= true
CrossingAgentInvoiceMinDate					= 01-10-2016

CrossingAgentInvoicePaymentMinDateAllow		= true
CrossingAgentInvoicePaymentMinDate			= 01-10-2016

CrossingAgentInvoiceCancelMinDateAllow		= true
CrossingAgentInvoiceCancelMinDate			= 01-10-2016
	
OctroiEntryMinDateAllow						= true
OctroiEntryMinDate							= 01-10-2016

LRWiseOctroiEntryMinDateAllow				= true
LRWiseOctroiEntryMinDate					= 01-10-2016

OctroiBillMinDateAllow						= true
OctroiBillMinDate							= 01-10-2016

OctroiInvoicePaymentMinDateAllow			= true
OctroiInvoicePaymentMinDate					= 01-10-2016

OctroiBillCancelMinDateAllow				= true
OctroiBillCancelMinDate						= 01-10-2016