GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

DefaultMinDate								= 01-04-2016
MinDateToViewOldData						= 01-04-2014

BookingPrintMinDateALlow					= false
BookingPrintMinDate							= 01-04-2016

DispatchMinDateAllow						= false
DispatchMinDate								= 01-04-2016

LoadingSheetMinDateAllow					= false
LoadingSheetMinDate							= 01-04-2016

ManualLoadingSheetMinDateAllow				= false
ManualLoadingSheetMinDate					= 01-04-2016

InterBranchLSMinDateAllow					= false
InterBranchLSMinDate						= 01-04-2016

ReceiveMinDateAllow							= true
ReceiveMinDate								= 01-04-2016

GodownReceiveMinDateAllow					= false
GodownReceiveMinDate						= 01-04-2016

CreateDDMMinDateAllow						= false
CreateDDMMinDate							= 01-04-2016

DDMSettlementMinDateAllow					= false
DDMSettlementMinDate						= 01-04-2016

CreateCreditorInvoiceMinDateAllow			= false
CreateCreditorInvoiceMinDate				= 01-04-2016

CreditorInvoicePaymentMinDateAllow			= false
CreditorInvoicePaymentMinDate				= 01-04-2016

CancelCreditorInvoiceMinDateAllow			= false
CancelCreditorInvoiceMinDate				= 01-04-2016

MultipleInvoicePaymentMinDateAllow			= false
MultipleInvoicePaymentMinDate				= 01-04-2016

LRCreditPaymentMinDateAllow					= false
LRCreditPaymentMinDate						= 01-04-2016

CreditCollectionModuleMinDateAllow			= false
CreditCollectionModuleMinDate				= 01-04-2016

CreditCollectionPaymentModuleMinDateAllow	= false
CreditCollectionPaymentModuleMinDate		= 01-04-2016

LHPVMinDateAllow							= false
LHPVMinDate									= 01-04-2016

BLHPVMinDateAllow							= false
BLHPVMinDate								= 01-04-2016

STBSCreationMinDateAllow					= false
STBSCreationMinDate							= 01-04-2016

STBSSettlementMinDateAllow					= false
STBSSettlementMinDate						= 01-04-2016

GenerateCRMinDateAllow						= false
GenerateCRMinDate							= 01-04-2016

GenerateCRForMultiLRMinDateAllow			= false
GenerateCRForMultiLRMinDate					= 01-04-2016

CancelCRMinDateAllow						= false
CancelCRMinDate								= 01-04-2016

CrossingAgentInvoiceMinDateAllow			= true
CrossingAgentInvoiceMinDate					= 01-04-2014

CrossingAgentInvoicePaymentMinDateAllow		= false
CrossingAgentInvoicePaymentMinDate			= 01-04-2016

CrossingAgentInvoiceCancelMinDateAllow		= false
CrossingAgentInvoiceCancelMinDate			= 01-04-2016
	
OctroiEntryMinDateAllow						= false
OctroiEntryMinDate							= 01-04-2016

LRWiseOctroiEntryMinDateAllow				= false
LRWiseOctroiEntryMinDate					= 01-04-2016

OctroiBillMinDateAllow						= false
OctroiBillMinDate							= 01-04-2016

OctroiInvoicePaymentMinDateAllow			= false
OctroiInvoicePaymentMinDate					= 01-04-2016

OctroiBillCancelMinDateAllow				= false
OctroiBillCancelMinDate						= 01-04-2016

LRSearchMinDateAllow						= false
LRSearchMinDate								= 01-04-2016

noOfDaysToViewData							=	0

firstDateToCompare							= 30-04_01-04
secondDateToCompare							= 31-10_01-10
allowCustomMinDate							= false

transportSearchMinDateAllow					= false
transportSearchMinDate						= 01-04-2016

fastTagDataMinDateAllow						= false
fastTagDataMinDate							= 01-01-2022