GroupName	= Kalpana CARGO
GroupCode	= kcpl
GroupId		= 3

NewLSPrint						= false

# for new dispatch ls print
dispatchPrintFromOldFlow	= true
showTBBAmountBranchWise			= true
branchIdsToShowTBBAmount		= 13699
