GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

dataForCrossingHire	= false
dataForDD			= false
freight				= false
loadingCharge		= false
unloading			= false
doorDelivery		= false
ddCharge			= false


#QuantityBasedCrossing
QuantityBasedCrossing			= false
# Comment for 
CommissionCalculation			= false
#DestBranchID_Commission	= CommissionValue
branch_commission				= 0_0;

cookies=false
executiveIds=0


#Amount Configration
showAmount						= false
ArticleTypeIds						= 0
minimumAmount						= 50

CrossingHireRateAllow			= false

WayBillTypeWiseDispatchDetails  = true

NewLSPrint						= false
# for getting Booking Time Crossing Hire Amount
bookingTimeCrossingHire			= false
doorPickup =false
handling	= false
lrCharge	=false

# for new dispatch ls print
dispatchPrintFromOldFlow	= true
IsAvoidCHOnWeightIfPresentInDB	= false
#show mini ls Link
displayMinifiedLsLink			= false

showShortLRDetailsInPrint		= false
lsPrintChangesAllowedAfterDeliveryTimeBillCredit	= true
showLoadingChargeAmountWayBillTypeWise				= false
showDestinationBranchWiseSummery	=false