GroupName	= Syndicate
GroupCode	= Syndicate
GroupId		= 69

freight			= true
loadingCharge	= true


CommissionCalculation			= true
#DestBranchID_Commission	= CommissionValue
								#indore_live, indore_99, aurangabad, waluj, ujjain, other
#default(other) commission should be last
branch_commission				= 31543_40, 16427_40, 16425_0, 16426_0, 16428_40, 00000_30

showPaidAmountByBranch			= true
#aurangabad, waluj
branches						= 16425,16426

NewLSPrint			= false
dispatchPrintFromOldFlow		= true