GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

#All Discount Values Are In Percent

#Centralized Property For All Modules
isDiscountLimitAllow						= false

#Module Wise Properties

BookingDiscountLimitAllow					= false
BookingDiscountLimitInPercent				= 100

DeliveryDiscountLimitAllow					= false
DeliveryDiscountLimitInPercent				= 100

ShortCreditPaymentDiscountLimitAllow		= false
ShortCreditPaymentDiscountLimitInPercent	= 100

BillPaymentDiscountLimitAllow				= false
BillPaymentDiscountLimitInPercent			= 100

STBSSettlementDiscountLimitAllow			= false
STBSSettlementDiscountLimitInPercent		= 100

DDMSettlementDiscountLimitAllow				= false
DDMSettlementDiscountLimitInPercent			= 100

RecAndDlyDiscountLimitAllow					= false
RecAndDlyDiscountLimitInPercent				= 100

CreditCollectionPaymentDiscountLimitAllow		= false
CreditCollectionPaymentDiscountLimitInPercent	= 100