GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

#Show  date column for Selection
showBillDetailsCol										= false
replaceCreditDebitLabels								= false
isDisplayRowForTdsDetailInPartyWiseLedgerReport			= false
showBillPaymentClubAmountInPartyWiseLedgerReport		= false
isDisplayRowForClaimEntryInPartyWiseLedgerReport		= false
isDisplayRowForDeductionEntryInPartyWiseLedgerReport	= false
isShowBillPaymentEntriesWithColorCode					= true
isAllowDeliveryTimeShortCreditInsertInRealTime			= false
isShowSeparateEntryForNegotiatedPaymentInPartyWiseLedgerReport	= true
showClubEntryForMultipleShortCreditPayment				= false
showTotalAmountWithoutTdsAndShowTdsNarration			= false
crAndDdmTimeShortCreditEnteredBySubRegionId				= 0
isAllowStbsCreationSingleEntryBySubRegionId				= 0
showSTBSBillPrint										= false