/**
 * @Author	Anant Chaudhary	04-01-2015
 */

var loadWayBillType					= new $.Deferred();	//	Way Bill type
var loadBookingType					= new $.Deferred();	//	Booking type
var loadLRNumberManual				= new $.Deferred();	//	Manual LR Number
var loadBranchCode					= new $.Deferred();	//	Branch Code
var loadSubregionDestination		= new $.Deferred();	//	SubRegion Deatination
var loadDestination					= new $.Deferred();	//	destination
var loadPickUp						= new $.Deferred();	//	Pick up
var loadFrightUpTo					= new $.Deferred();	//	frightupto
var loadVehicleType					= new $.Deferred();	//	vehical
var loadVehicleTypeWithConstantVal	= new $.Deferred();	//	vehical
var loadFutureDate					= new $.Deferred();	//	Future Date
var billSelectionText				= new $.Deferred();	//	bill selection text
var loadVehicleNumber				= new $.Deferred();	//	vehicle Number
var loadConsignor					= new $.Deferred();	//	consignor
var loadConsignee					= new $.Deferred();	//	consignee
var loadAddArticle					= new $.Deferred();	//	addarticle
var loadWeightAndAmount				= new $.Deferred();	//	wght and amt
var loadSTPaidBy					= new $.Deferred();	//	st paid by
var loadInvoiceNo					= new $.Deferred();	//	invoice
var loadInvoiceDate					= new $.Deferred();	//	invoice date
var loadCargoType					= new $.Deferred();	//	cargo type
var loadDeclaredValue				= new $.Deferred();	//	declared value
var loadDeliveryTo					= new $.Deferred();	//	delivery to
var loadRemark						= new $.Deferred();	//	remark
var loadAdditionalRemark			= new $.Deferred();	//	remark
var loadPaymentType					= new $.Deferred();	//	paymenytype
var loadTopayAdvance				= new $.Deferred();	//	topayAdvance
var loadServiceType					= new $.Deferred();	//	Servicetype
var loadPartialPaymentType			= new $.Deferred();	//	partialpaymenytype
var loadTotalQuantity				= new $.Deferred();	//	total quantity
var loadSearchCollectionPerson		= new $.Deferred();	//	search collection person
var loadChequeDetails				= new $.Deferred();	//	cheque details
var loadCreditCardDetails			= new $.Deferred();	//	cheque details
var loadDebitCardDetails			= new $.Deferred();	//	cheque details
var loadSaveButton					= new $.Deferred();	//	save button
var loadWayBillCharges				= new $.Deferred();	//	way bill charges
var loadAddNewPartyOverlay			= new $.Deferred();	//	add new party overlay
var loadSaidToContainOverlay		= new $.Deferred();	//	said to contain overlay
var loadCommodityType				= new $.Deferred();	//	Commodity Type
var loadPrivateMark					= new $.Deferred();	//	Private mark
var loadRiskAllocation				= new $.Deferred();	//	Risk Allocation
var loadForms						= new $.Deferred();	//	Forms
var loadFormTypes					= new $.Deferred();	//	Form Types
var loadSingleFormTypes				= new $.Deferred();	//	Single Form Types
var loadForm403402					= new $.Deferred();	//	Form 403 402
var loadFormCTForm					= new $.Deferred();	//	CTForm 
var loadRatesDef					= new $.Deferred();
var loadBillSelectionAtBooking		= new $.Deferred();
var partialPaymentModal				= new $.Deferred();
var viewAllConsignmentGoodsModal	= new $.Deferred();
var loadWayBillTypeOption			= new $.Deferred(); // WayBillType
var loadSourceBranch				= new $.Deferred(); // Source Branch
var loadLRDate						= new $.Deferred();
var loadRoadPermitNumber			= new $.Deferred(); // Road Permit number
var loadExciseInvocie				= new $.Deferred(); // Excise invoice
var loadConsignmentInsured			= new $.Deferred(); // Consignment insured
var loadManualEntryType				= new $.Deferred();	//	Manual entry type -- Normal , Reverse entry
var loadPreBookingCharges			= new $.Deferred();	//	For Load Pre Booking Chaeges
var loadPanNumber					= new $.Deferred();	//	Pan Number
var loadTanNumber					= new $.Deferred();	//	Tan Number
var loadPaytmDetails				= new $.Deferred();	//	cheque details
var sequenceTypeSelection			= new $.Deferred();
var loadPODRequired					= new $.Deferred(); // POD Required Feild
var loadBankPaymentOptions			= new $.Deferred();	//	Bank Payment Options
var loadPaymentRequiredFeild		= new $.Deferred(); //	PaymentRequired Feild
var loadReserveCheckBox				= new $.Deferred(); //	Reserve Booking CheckBox
var loadPercentageRiskCover			= new $.Deferred(); //	% Risk Cover
var loadSmsRequiredFeild			= new $.Deferred(); //	SMS Required CheckBox
var loadTransportationMode			= new $.Deferred(); //	SMS Required CheckBox
var addMutipleEwayBillNumber		= new $.Deferred(); //	Add multiple E-Way Bill Number
var loadChequeBounce				= new $.Deferred(); //	cheque Bounce Details
var	loadExcludeCommissionOption		= new $.Deferred(); //  Exclude Commission Checkbox
var idProofOperation				= new $.Deferred();
var loadEwayBillExempted			= new $.Deferred();// EwayBillExempted
var loadccAttached					= new $.Deferred();	//	cc attached
var loadOTLRNumber				  	= new $.Deferred();	//	Manual LR Number
var loadDocumentType			  	= new $.Deferred();
var loadSingleEwayBillNumber		= new $.Deferred();	//	Single Eway Bill Number
var recharge						= new $.Deferred();	//	Recharge
var loadAddNextNumberOfLR			= new $.Deferred();	//	Add Next Number Of LR
var loadETAButton					= new $.Deferred(); // estimated time of arrival button
var loadDirectorList				= new $.Deferred(); //drop down of director list
var loadCategoryFeild				= new $.Deferred();
var loadGSTTypeFeild				= new $.Deferred();
var loadBookedBy					= new $.Deferred();
var loadServiceTypeFeild			= new $.Deferred();
var loadTransportationCategory		= new $.Deferred();
var loadMultipleInvoiceDetails		= new $.Deferred();
var loadInsurance					= new $.Deferred();	//	insurance
var loadCod							= new $.Deferred();	//	insurance
var LRSequenceCounterCheckBox		= new $.Deferred(); // Source Branch WIse check Box In Manual
var loadGstPercentSelection			= new $.Deferred(); // Load Percent Selection
var loadSubCommodityType			= new $.Deferred(); // Load SubCommodity Selection
var shortCreditPopup				= new $.Deferred();
var loadInvoiceQtyFeild				= new $.Deferred(); 
var loadSealNumberFeild				= new $.Deferred(); 
var loadVehiclePoNumberFeild		= new $.Deferred(); 
var loadApprovalTypeFeild			= new $.Deferred(); 
var loadForwardTypeFeild			= new $.Deferred();
var loadHsnCodeFeild				= new $.Deferred(); 
var loadInsurancePolicyNoFeild		= new $.Deferred();
var loadTemperatureFeild			= new $.Deferred();
var loadDeclarationFeild			= new $.Deferred();
var loadDataLoggerNoFeild			= new $.Deferred();
var loadConnectivityFeild			= new $.Deferred();
var loadBookingPrintDate			= new $.Deferred();
var loadDivisionSelection			= new $.Deferred();
var loadBookingTimeOtpFeild			= new $.Deferred();
var loadMovementTypeFeild			= new $.Deferred();	

var jsondata 						= null;
var configuration					= null;
var executive						= null;
var ChargeTypeMaster				= null;
var CustomerDetails					= null;
var RateMaster						= null;
var State							= null;
var WayBillType						= null;
var TransportCommonMaster			= null;
var Branch							= null;
var CorporateAccount				= null;
var PartyMaster						= null;
var WayBill							= null;
var ChargeConfiguration				= null;
var GroupConfigurationProperties	= null;
var vehicleTypeConstant				= null;
var PackingTypeMaster				= null;
var FormTypeConstant				= null;
var InfoForDeliveryConstant			= null;
var ConfigParam						= null;
var BusinessFunctionConstants		= null;
var BookingChargeConstant			= null;
var PackingGroupMappingArr			= null;
var RateHm							= null;
var packingGroupMappingCounter		= 0;
var rate_values						= null;
var TaxPaidByConstant				= null;
var BookingTypeConstant				= null;
var ChargeTypeConstant				= null;
var PODRequiredConstant				= null;
var wayBillRates					= null;
var combinationWayBillRates			= null;
var cnorWayBillRates				= null;
var chargesConfigRates				= null;
var chargesConfigRates1				= null;
var consignorChargesConfigRates		= null;
var chargesRates					= null;
var chargeWeightConfig				= null;
var articleWiseWeightDiffConfig		= null;
var formTypeWiseCharges				= null;
var ctFormTypeWiseCharges			= null;
var formTypeWiseChargesByBranch		= null;
var ctFormTypeWiseChargesByBranch	= null;

var applyConsignorRateOnTopay		= false;
var showRatesNotFound				= false;
var isBookingDiscountAllow			= false;
var isBookingDiscountPercentageAllow= false;
var allowReverseEntryLRBooking		= false;

var weightTypeArr					= new Array();
var quantityTypeArr					= new Array();
var fixTypeArr						= new Array();

var consignorAc						= null;
var isWayBillSaved					= false;
var isWayBillSaving 				= false;
var partyType						= null;
var agentCommissionValueAllowed 	= 0;
var consigneePartyMasterId 			= 0;
var minWeight						= 0;
var minSlab							= 0-0;
var aticleWiseMinWeight				= 0;
var aticleWiseMaxWeight				= 0;
var defaultlrCharge					= 0;
var noOfArticlesAdded				= 0;
var idNum							= 0;
var diffAmtAfterRoundOff			= 0;
var taxableAmount					= 0;
var chargedWeight					= 0;
var aplyRateForCharges				= null;
var defaultDeliveryAt				= 0;
var defaultSTPaidBy					= 0;
var pervwayBillId					= 0;
var previsRePrint					= false;
var setDefaultStPaidBy 				= false;
var defaultActualWeight				= 0;
var isAutoSequenceCounter			= true;
var minimumQuantityAmount			= 0;
var quantityAmountCharges			= null;
var MinQtyAmtTobeAssigned			= 0;
var chargeWeightToIncrease			= null;
//those are to define party is billing party aur creditor party for json request
var TBB_CREDITOR	= 1;
var TBB_BILLING		= 2;
var isOwnBranchLocationsRequired    = false;
var chargeTypeFlavour				= null;
var stPaidBySelectionByParty		= false;
var getBillingPartyDetails		 	= 3;
var getGeneralPartyDetails			= 0;
var lrExists						= false;
var isManual						= false;
var isReverseEntry					= false; 

var disableHamliChargeOnTopay		= false;
var totalConsignmentQuantity		= 0;	
var isNextPreviousNavigationAllow	= false;
var packingTypeArr					= new Array();
var accountGroupId					= 0;
var defaultPaymentType				= 0;
var branchId						= 0;
var cityId							= 0;
var numberTypes 					= null;
var selectedSource					= null;
var partyMinAMount					= new Array();
var jsonPartyMinAMt					= new Object();
var jsonPartyMinWeight				= new Object();
var jsonPartyMinSlab				= new Object();
var strDate 	= null;
var weightFromDb 					= 0;
var purefrieghtAmount				= 0;
var qtyAmt							= 0;
var chargeWeightFlavour				= 0;
var increaseChargeWeight			= 0;
var fixFromDb 						= 0;

var articleWiseWeightFlavour		= 0;	
var TotalQty						= 0;
var showCityAndDestinationBranch	= false;
var allowAjaxCheckOnDestinationBranchSelect = false;
var formTypeWiseChargesFlavour		= 0;
var ctFormTypeWiseChargesFlavour		= 0;
var formChargeAmount				= 0;
var totalFormChargeAmount			= 0;
var isManualWayBill					= false;
var destinationBranchId 			= 0; 
var showWayBillTypes				= null;
var isPaidBookingPermission			= false;
var isTopayBookingPermission		= false;
var isTbbBookingPermission			= false;
var isFocBookingPermission			= false;
var serviceTaxAmount				= 0;

var destBranchAccountGroupId		= 0;
var SequenceCounter					= null;
var isBookingFromDummyLS			= false;
var LR_SEARCH_TYPE_ID				= 1;
var loggedInBranch					= null;
var PaymentTypeConstant				= null;

var AOCPercentageValue				= 0;
var FOVChargeValue					= 0;
var applyDoorDeliveryCharge			= false;
var isServicetaxSet					= false;
var loggedInBranch					= null;
var totalFreightAmountByPackingType = 0;
var totalHamaliAmountByPackingType  = 0;
var isPanNumberRequired				= false;
var isAppliedGeneralRateForParty	= false;
var form403_402ChargeAmt 			= 0;
var ctFormTypeWiseChargeAmt			= 0;
var isServiceTaxPaidBy				= false;
var ddSlabAmount					= 0;
var formTypeMastersArray			= null;

var isDummyLR						= false;
var	lrprintlist						= null;	

var destinationBranch				= null;
var destinationBranchIds			= null;

var isBranchRate						= false;
var billingPartyWayBillRates			= false;
var consignorPartyWayBillRates			= false;
var consigneeWayBillRates				= false;

var isBranchChargeConfigRate			= false;
var billingPartyChargeConfigRates		= false;
var consignorPartyChargeConfigRates		= false;
var consigneeChargeConfigRates			= false;

var billingPartyRates					= null;
var consignorPartyRates					= null;
var consigneePartyRates					= null;

var billingPartyLRSectionRate			= null;
var consignorPartyLRSectionRate			= null;
var consigneePartyLRSectionRate			= null;

var isManualLRNumberAlreadyExist		= false;
var applyRateForSpecificArticle			= false;
var stringNew							= '(New)';
var chargesToApplyArticleWiseRateOnWeightType	= 0;
var isSlabRateNotExists                 = false;
var consignmentGoodsArrList				= null;
var consignmentWithZeroAmtFound 		= 0;
var totalConsignmentAmt 				= 0;
var sourceBranchStateId					= 0;
var destinationBranchStateId			= 0;
var discAmount 							= 0;
var ArticleWeightWiseErrMsg				= false;
var agentCommissionValue				= 0.0;
var cnsgnmentGoodsId 					= new Array();
var	execFeildPermissionWithBill			= null;
var execFeildPermissionWithOutBill		= null;
var AutoLRNumberSelectionInManualPer 	= null;
var selfCorporateAccountId				= 0;

var maximumSlabValue					= 0;
var isConsignmentExempted				= false;
var isConsignmentEWayBillExempted		= false;
var preIsConsignmentExempted			= false;
var defaultServiceType					= 0;
var branchPincodeConfigList				= null;
var ExecutiveTypeConstant				= null;
var consignmentGoods					= null;
var paymentTypeArr						= null;
var isPODRequiredBasedOnBillingParty	= false;
var isPODRequiredBasedOnConsignor		= false;
var isPODRequiredBasedOnConsignee		= false;
var moduleId							= 0;
var incomeExpenseModuleId				= 0;
var ModuleIdentifierConstant			= null;
var isConsignorGSTNPresent				= false;
var isConsigneeGSTNPresent				= false;
var actualSlabValue						= 0;
var isGSTNAlreadyExist					= false;
var ModuleIdentifierConstant			= null;
var weightTypeForRateApply				= 0;
var partyCode							= null;
var isApplyFixRateonArticleRateMinMaxArticleWise		= false;
var isReserveBookingChecked				= false;
var chargedWeightRoundOffValue				= 0;
var bankAccountNotMandatory				= false;
var cardNumberNotMandatory				= false;
var applicableOnChargeTypeMasterIdArr	= null;
var configuredChargeTypeId				= 0;

var packingTypeList						= null;
var consignmentGoodsListHM				= null;
var chargeMinAmountforFSCharge			= 0;
var allowRateInDecimal					= false;
var lrWiseDecimalAmountAllow			= false;
var invalidInvoiceNumber				= false;
var isConsignorTBBParty					= false;
var isConsigneeTBBParty					= false;
var isSmsRequiredBasedOnParty			= false;
var smsRequiredId						= 0;
var chgwgtActWgtConditionForLess		= false;
var operationBranchId					= 0;
var	srcBranchId							= 0;
var operationalBranchId 				= 0;
var rateId_mast							= null;
var servicePermission					= null;
var tdsConfiguration					= null;
var tdsChargeInPercent					= null;
var checkBoxArray						= new Array();
var subRegionIdsForOverNite				= null;
var destnationBranchIdForOverNite		= 0;
var setPartyOnGSTNChange				= false;
var isSwapCustomerNamePanel				= false;
var destinationWiseLRLevelCharges		= false;
var isTokenWayBill						= false;
var destBranch							= null;
var consignmentDetails					= null;
var accountGroup						= null;
var podConfiguration					= null;
var loggedInExecutiveSubregion			= null;
var isApplyFixRate						= false;
var fixRateChargeIds					= null;
var loadingChargeAmount					= 0;
var applyDiscountThroughMaster			= null;
var commissionValue						= 0;
var freightToCalculate					= 0.00;
var TotalSize							= 0;
var totalConsignmentSize				= 0;
var idProofConstantArr					= null;
var IDProofConstant						= null;
var isAllowToEnterIDProof				= false;
var maxFileSizeToAllow					= 0;
var doneTheStuff 						= false;
var isEmptySaidToContainAdded			= 0;
var discountInPercent					= 0;
var discountAmt							= 0;
var TaxMasterConstant					= null;
var shortCreditConfigLimit				= null;
var isCCAttached						= false;

var bankAccountList						= null;
var validateInvoiceOnDeclaredValueOnSave= false; 

var	isAccountNumberDisable				= false;
var validateInvoiceOnDeclaredValueOnSave= false; 
var artActWeightArr						= {};
var artChrgWeightArr					= {};
var consigAddedtableRowsId				= [];
var isTBBPartyExempted					= false;
var loadBillingBranch					= new $.Deferred();
var containerDetailsArray				= [];
var notAplicablePackingTypeId			= false;

var isLrPdfAllow						= false;
var distance							= 0;
var chargeIdsForCCAttachedArr			= null;
var isAgentBranchBoolean				= false;
var agentBranchId						= 0;
var stateGSTCode						= 0;
var configuredChargeTypeIdWithCharge	= {};
var fixedChargeRateObj					= {};
var maxRangeForLrSequence				= 0;
var minRangeForLrSequence				= 0;
var partyWiseSequence					= false;
var partySequenceExists					= false;
var tbbPartyCode						= null;
var isTransporter						= false;
var isValidEWayBill						= false;
var eWayBillNumberArray					= new Array();
var eWayBillValidationHM				= new Map();
var isFromViewEWayBill					= false;
var destSubRegionId						= 0;
var gstPaidSelectExists					= false;
var consignorRateConfigured				= false;
var consigneeRateConfigured				= false;
var consignorPodRequired				= false;
var consigneePodRequired				= false;
var declareValueChanges					= true;
var isFreightChargeEnableGanth					= false;
var isFreightChargeEnableBranchListForTopayNAG	= false;
var isFreightChargeEnableBranchList				= false;
var isFreightChargeEnableBranchListForTopay		= false;
var isBranchListForSkipAmountValidation			= false; 
var isNewFreightChargeBranchList				= false;
var isPackingTypefreightChargeBranchList		= false;
var isOwnBranchCityList							= false;
var checkBranchForFixLoadingCharge				= false;
var isBranchListForSkipAmountValidation			= false;
var isNewLoadingChargeBranch					= false;
var isLoadingIncreaseBranchList					= false;
var isNewFreightChargeBranchList			= false;
var isPackingTypefreightChargeBranchList	= false;
var totalQuantityOfCartoon					= 0;
var amountWithDiscount						= 0;
var checkBranchForFreightIncreaseOrDecrease		= false;
var amountWithIncreaseAmount	= 0;
var totalLoadingWithDiscount	= 0;
var lrPrintLinkConfig		= ''
var lrPrintLink	= '';
var countArticleRate	= {};
var consignorAutofillShortcutAllow	= false;
var consigneeAutofillShortcutAllow	= false;
var calcDDCharge					= false;
var calcDDChargeArr					= new Array();

var	isExempted							= null;
var isTBBPartyExempted					= false;
var isConsignorExempted					= false;
var isConsigneeExempted					= false;
var consignorGstNMandotory	= false;
var consigneeGstNMandotory	= false;
var articleTypeForGroup		= null;
var loadingValue	= 0;

var BillingCFTUnit						= 0;
var CFTUnit		= 0;

var CFTValue		= 0;
var cftWeightArr						= {};
var chrgWtArr							= {};
var cftFixAmountArr						= {};

var getBillingPartyId 					= 4 ;

var applicableChargeRateObj				= {};
var quantityWiseChargeAmount			= null;
var quantityWiseChargeObj	= {};
var weightWiseChargeAmount	= {};
var isFreightChargeEnable = false;
var isTokenThroughLRBooking = false;
var packingTypeWiseAmount	= [];
var weightWiseChargeAmount	= {};
var	branchWisePrepaidAmount				= null;
var	rechargeAmount						= null;
var prepaidAmountId						= 0;
var rechrgAmnt							= 0;
var isShowConfirmPopup					= false;
var isValidateEwaybillFromPopup         = true;
var isTransporterForConsignor			= false;
var isTransporterForConsignee			= false;
var wayBillTypeList = new Array();
var taxTypeHm                           = null;
var consignorTaxType                   = 0;
var consigneeTaxType                   = 0;
var billingTaxType                     = 0;
var LRTypeChargeIdHMToShowCharge		= null;
var isConsigneeIncreaseChargeWeight		= false;
var	isConsignorIncreaseChargeWeight		= false;
var selectedTokenLRType					= 0;
var showEwayBillPopupOnLoad				= true; 
var chargeTypeIdsFromRateMaster			= 0;
var  branchcache						= null;				
var taxModelHm							= null;
var hamaliChargeAmt						= 0;
var checkSubRegionIdsForChargeTypeFlavour	= false;
var packingTypeGoods					= null;
var defaultTransportationModeId 		= 0;
var slabWeightList						= null;
var valuationChargeList					= null;
var partyIdForCommission				= 0;
var loggedInExecutiveBranch				= null;
var isCoverPackingTypeAdded				= false;
var imageCount							= 0;
var imageArr							= new Array();
var validateRateFromRateMasterForLR		= false;
var validateRateFromRateMasterForLRWithoutDisableFields	= false;
var inclusiveChargeRateObj	= {};
var isLRTypeExistForPackingRate			= false;
var isPartyChargeInclusive				= false;

var chargeConfigPartyId					= 0;
var freightRatePartyId					= 0;
var consignorNameAutocomplete			= false;
var isFixedValuationAmount				= false;
var srcLatitude 		= 0;
var srcLongitude		= 0;
var destLatitude 		= 0;
var destLongitude 		= 0;
var dist		= 0;
var doorDeliveryAddressPinCode = 0;
var deliveryBranchPincode	= 0;
var BOOKING_TYPE_SUNDRY_ID	= 1;
var BOOKING_TYPE_FTL_ID	= 2;
var DIRECT_DELIVERY_DIRECT_VASULI_ID	= 3;
var GOODS_CLASSIFICATION_FRAGILE	= 2;
var BOOKING_TYPE_MAIL_ID	= 8;
var BOOKING_TYPE_PARCEL_CARGO_ID	= 9;
var INDIA	= 1;
var NIGERIA	= 2;
var showLRNumberPopup					= false;
var previousWghtAmt						= 0;
var FRAGILE	= 279;
var GeneralConfiguration	= null;
var groupIdsForNextPrevAfterConsignorName	= [450];
var groupIdsForNextPrevAfterConsigneeName	= [450];
var groupIdsForNextPrevAfterPackingType		= [383,402,388,412,389,427,438];
var groupIdsForNextPrevAfterEwayBillEscape	= [439,270,50,355,280,385,281,202,201,442,447,9,66,454,231,467,399,3,285,227,466,402,293,580,592,566,544,609,617,271,39,627,572,644,669,581,22,709,724,520,740];
var groupIdsForNextPrevAfterAddArticleToCharges	= [484,487,481];
var groupIdsForNextPrevAfterEwayBillSubmit	= [439,270,50,355,280,385,281,202,201,442,447,9,66,454,231,467,399,3,285,227,466,402,293,580,592,566,544,609,617,271,39,627,572,644,669,581,22,709,724,520,740,792,918];
var groupIdsForNextPrevAfterArticleAdd		= [402,388,412,389];
var groupIdsForNextPrevAfterChargeWeight	= [412,389,399,563];
var groupIdsForNextPrevAfterWeightRate		= [402,388,412,389,740];
var groupIdsForNextPrevAfterFixedValue		= [402,388,412,389,484,487,481];
var prevLRNo	= null;
var consignmentEWayBillExemptedObj		= {};
var businessTypeId	= 0;
var operationalBranchCode				= null;
var partyWiseDataHM						= {};
var partyWiseMinimumValueDataHM			= {};
var consignmentGoodsListForParty		= null;
var validateEwaybillNumberThroughApi	= false;
var consignmentDataHM					= {};
var destinationBranchGstn				= null;
var tbbPartyGstn						= null;
var tbbPartyBranchStateCode				= 0;
var isFixedArticleSlab	= false;

var eWayBillHM							= {};
var stateWiseRateMap					= null;
var destinationBranchStateGSTCode		= 0;
var isSlabExists						= false;
var isFixedArticleSlab	= false;
var weightFromDbOnFrt	= 0;
var fixedSlabAmtExist	= false;
var isFtlBooking	= false;
var destBranchServiceTypeId				= 0;
var destBranch							= null;
var isFixedArticleSlab	= false;
var invoiceDetailArray = [];
var tempLrCharge		= 0;
var isFixedSlab							= false;
var isGenerateQRCodePhonePeForUPIAllow	= false;
var generateAndValidateQROnUPIRechargePermission	= false;
var eWayBillDetailsIdHM					= {};
var slabWisePartyMinimumAmtHM			= {};
var doNotHideLRNumberManual				= false;
let rateId_mastNew            = new Object();
var minimumValueConfigHM ={};

var isConsignorGstnValidatedFromApi		= false;
var isConsigneeGstnValidatedFromApi		= false;
var chrWeightAmt	= 0;
var declaredValueRates = null;
var isExecutiveBranchWiseSeqCounterChecked	= false;
var isValidatedPartyGstn				= false;
var validUpdateGstn						= false;
var nextLrNumberSeq						= 0;
var groupWiseCompanyNameHm				= new Map();
var groupWiseCompanyNameId				= 0;
var allowToCheckSameCompanyGstnOnEwayBill	= false;
var totalInsuranceCharge				= 0;
var destSubRegion						= null;
var upiRechargeMessage					= '';
var deductPercentAmount					= 0;
var isDeductCharges						= false;
var packingTypesNameHM					= null;
var groupListForGSTN = [26,27,35,41,45,48,61,68,69,238,253,264,358,359,363,409,463,580,645,675,695,314,335];
var policyGenerationRequestId	= 0;
var formChargeRatesDB			= 0;
var defaultTaxValue				= 0;
var chargeWeightConfigForRoundOff	= null;
var roundOffChargeWeightDB			= 0;
var billIdForInvoicePrint			= 0;
var singleInvoiceDetailsArr = [], invoiceDetailArrayForInsurance	= [];
var subCommodityHM = new Map();
var isInsuranceServiceAllow = false;
var isPaidByDynamicQRCode 			= false;
var multiLRDeliveryTotalAmount		= 0;
var actualWeightRateAmt 	= 0;
var actualWeightRateAmt 	= 0;
var	cnorPartyDeliveryAt 	= 0;
var	cneePartyDeliveryAt 	= 0;
var	tbbPartyDeliveryAt 		= 0;
var partyDeviationPercent	= 0;
var partyDeductionPercent	= 0;
var checkAndApplyDeviationWiseRate = false;
var isPinodeForIns	= true, isAddressForIns	= true;
var dispatchLedgerIdForManualLS	= 0;
var dispatchLedger	= null;
var appendLrSuccess	= false;
var lsBranchId	= 0;
var crossingAgentId	= 0;
var allowToSendQROnWhatsapp	= false;
var riskCoverage			= 0;
var riskcoveragePercentage	= false;
var loadRecoveryBranch		= new $.Deferred();
var isOtpVerified        	= false;
var riskcoveragePercentage	= false;
var loadRecoveryBranch		= new $.Deferred();
var totalChargesToDeductFromFreight	= 0;
var jsonObjectNew			= null;
var uploadPdfDetailsList	= null;
var multiLRDeliveryTdsTotalAmount= 0;
var isFromDynamicPaymentTypeSelection = false;
var validateInvoiceNumberForConsignee = false;
var validateInvoiceNumberForConsignor = false;
var validateInvoiceNumberForTBB	= false;
var validatePartNumberForConsignee = false;
var validatePartNumberForConsignor = false;	
var validatePartNumberForTBB = false;
var validatePartNumber	= false;
var validateInvoiceNumber	= false;
var validateInvoiceNumber	= false;
var allowStandardCustomFlowPhonePe	= false;
var showRegionWiseMovementType = false;
let isBranchCommissionOnWeight = false
var disableFreightCharge	= false;
var articleWiseFreightRate	= {};