GroupName	= Raman Holding Pvt.Ltd.(Speed Cargo)
GroupCode	= RHPL
GroupId		= 39

#Show delivery date column
serviceTaxSummaryReportWithoutPaidLRDetails		= false
showBkgTotalAmt									= true
showDlyTotalAmt									= true
showBillTotalAmt								= true
setDefaultDataLevelFilter						= true
defaultDataLevelFilter							= 3