GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

#Show delivery date column
serviceTaxSummaryReportWithoutPaidLRDetails		= false
showBkgTotalAmt									= false
showDlyTotalAmt									= false
showBillTotalAmt								= false
setDefaultDataLevelFilter						= false
roundOffAmount									= false