GroupName	= SRS
GroupCode	= srs
GroupId		= 17

## Display of Data Config

Year			= 2020
Month			= 04
date			= 01

isDonotShowWayBillTypeWiseDataInReports		= false
wayBillTypeIdToDonotShowDetails				= 1

#SRS_KALASIPALLYAM	= 14119, SRS_ARCBOOKING		= 14422
branchIdsToDonotShowDetails					= 14119,14422
diffrenceBetweenDays						= 2

#SRS_IVADMIN = 11816, SRS_VINAY	= 12585
executiveIdsToShowDetails					= 11816,12585,19525
wayBillStatusIdsToShowDetails				= 9
showDeliverLRAtDestination					= true
reportsToShowDeliverLRAtDestination			= 25