GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

## Display of Data Config

isdataConfig	= false
filter			= 1
Year			= 2020
Month			= 04
date			= 01

wayBillTypeIdToDonotShowDetails				= 0
branchIdsToDonotShowDetails					= 0
diffrenceBetweenDays						= 0
executiveIdsToShowDetails					= 0
wayBillStatusIdsToShowDetails				= 0
displayDataIfUndelivered					= false