GroupName	= Raman Holding Pvt.Ltd.(Speed Cargo)
GroupCode	= RHPL
GroupId		= 39

## Display of Data Config
isdataConfig	= true
filter			= 1
Year			= 2023
Month			= 04
date			= 01
showCancelllationData	= true
