GroupName	= Shree Sahajanand Logistics
GroupCode	= sst
GroupId		= 41

## Display of Data Config

Year			= 2020
Month			= 04
date			= 01
isdataConfig	= true
filter			= 2
displayDataIfUndelivered = true