GroupName	= Shreenath Travellers
GroupCode	= ST
GroupId		= 45

## Display of Data Config


Year			= 2020
Month			= 04
date			= 01
isdataConfig		= true
filter			= 2
displayDataIfUndelivered = false