GroupName	= Falcon Cargo
GroupCode	= falcon
GroupId		= 50

## Display of Data Config

Year			= 2020
Month			= 04
date			= 01
isdataConfig		= true
filter			= 2
displayDataIfUndelivered = true

yearToViewOldData		= 2014
monthToViewOldData		= 04
dateToViewOldData		= 01