GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

## Display of Data Config

isdataConfig	= false
filter			= 1
Year			= 2016
Month			= 04
date			= 01

isDonotShowWayBillTypeWiseDataInReports		= false
wayBillTypeIdToDonotShowDetails				= 0
branchIdsToDonotShowDetails					= 0
diffrenceBetweenDays						= 0
executiveIdsToShowDetails					= 0
wayBillStatusIdsToShowDetails				= 0
displayDataIfUndelivered					= false
wayBillTypeIdToShowZeroAmount				= 0
executiveTypeIdToShowZeroAmount				= 0

yearToViewOldData							= 2014
monthToViewOldData							= 04
dateToViewOldData							= 01
showDeliverLRAtDestination					= false
reportsToShowDeliverLRAtDestination			= 0
showExecutiveIdWiseAmount					= false
executiveIdsToShowAmount					= 0
noOfDaysToViewData							= 0
firstDateToCompare							= 30-04_01-04
secondDateToCompare							= 31-10_01-10
allowCustomMinDate							= false
showCancelllationData						= false

showZeroAmountInModule		= false
moduleIdsToShowZeroAmount	= 0
showZeroAmountInReport		= false

#reorts - 72,73,109,103,70,68,62,65,118,119,126,88,87,168,99,156,112,2,3,5
reportIdsToShowZeroAmount	= 0