GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

#Display Number Type Selection Pannel
numberTypeSelectionBoxDisplay		= false

#Link to show party details
showLinkForPartyDetails				= false

showLocationField					= true

tinNoValidationAllow				= false

#Validate Branch On Edit -- For LMT As They Have BranchId = 0 In Corporate Account Table
validateBranchOnEdit				= true

# For Email Address Feild Mandatory
emailAddressFeildMandatory	= false
shortCreditAllowOnTxnType			= false
isInsuredByRequired			= false
serviceTaxPaidByCreditor	= false
hideTinNo					= false
contactPersonFeildMandatory	= true
phoneNumberFeildMandatory	= true
customPartyType				= false
showRegionSubregionBranchSelectionToAllUser		= false

# Validate GSTN Number To be Unique Before Save Party
checkGSTNumberForUnique				= true
rateSelectionAllowedOnWeightType	= false
partyCode							= false

# Show Delivery At Selection
showDeliveryAt						= false

# Show Feild For Charged Weight Round Off Configuration
showChargedWeightRound				= false
roundOffValues						= 0

#show Tan Number Field
showTanNumberField						= false
#show SMS Requied Field
showSmsRequiedField						= false
#show Is Transporter Field For GSTR 1
showIsTransporterField					= false