GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

# For Add Document Code Wise LS Sequence Counter
documentCodeWiseLsSeqCounter                = false
# Document Code For LS Sequence Counter
documentCodeForLsSeqCounter					= 0

# For Add Document Code Wise TUR Sequence Counter
documentCodeWiseTurSeqCounter				= false
# Document Code For TUR Sequence Counter
documentCodeForTurSeqCounter				= 0

# For Add Document Code Wise CR Sequence Counter
documentCodeWiseCrSeqCounter				= false
# Document Code For CR Sequence Counter
documentCodeForCrSeqCounter					= 0

# For Add Document Code Wise Inter LS Sequence Counter
documentCodeWiseInterLsSeqCounter			= false
# Document Code For Inter LS Sequence Counter
documentCodeForInterLsSeqCounter			= 0

# For Add Document Code Wise Crossing LS Sequence Counter
documentCodeWiseCrossingLsSeqCounter		= false
# Document Code For Crossing LS Sequence Counter
documentCodeForCrossingLsSeqCounter			= 0

# For Add Document Code Wise STBS Sequence Counter
documentCodeWiseStbsSeqCounter				= false
# Document Code For STBS Sequence Counter
documentCodeForStbsSeqCounter				= 0

# For Add Document Code Wise Fund Transfer Sequence Counter
documentCodeWiseFundTransferSeqCounter		= false
# Document Code For Fund Transfer Sequence Counter
documentCodeForFundTransferSeqCounter		= 0

# For Add Document Code Wise Receipt Voucher Sequence Counter
documentCodeWiseReceiptVoucherSeqCounter	= false
# Document Code For Receipt vpucher Sequence Counter
documentCodeForReceiptVoucherSeqCounter		= 0

# For Add Document Code Wise Payment Voucher Sequence Counter
documentCodeWisePaymentVoucherSeqCounter	= false
# Document Code For Payment Voucher Sequence Counter
documentCodeForPaymentVoucherSeqCounter		= 0

customDocumentCode											= false