GroupName	= PAULO TRAVELS GOA
GroupCode	= ptg
GroupId		= 67

# This Property is for enter the Agent Commission Stock Entry For Agent Commission Billing System
allowPendingAgentCommissionBillingStockEntry		= true
bankAccountNotMandatory								= true
waybillTypesAllowedForAgentCommissionBillingStockEntry	= 1