GroupName	= SRS Travels And Logistics Private Limited
GroupCode	= SRS
GroupId		= 17

DefaultMinDate							= 01-04-2020

PendingDeliveryStockReportMinDateAllow			= true
PendingDeliveryStockReportMinDate				= 01-01-2023

PendingDdmSettlementReportMinDateAllow			= true	
PendingDdmSettlementReportMinDate				= 01-01-2023