GroupName	= Durgamba Motors
GroupCode	= Durgamba
GroupId		= 18

DefaultMinDate										= 01-04-2025

BookButNotDispatchReportMinDateAllow				= true
BookButNotDispatchReportMinDate						= 01-04-2025

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 01-04-2025

ToPayDoorGodownStockReportMinDateAllow				= false
ToPayDoorGodownStockReportMinDate					= 01-04-2025

GodownStockReportMinDateAllow						= false
GodownStockReportMinDate							= 01-04-2025

PartyWiseLRDetailsReportMinDateAllow				= true
PartyWiseLRDetailsReportMinDate						= 01-04-2025

PendingDispatchStockReportMinDateAllow				= true
PendingDispatchStockReportMinDate					= 01-04-2025

PendingBLHPVLedgerReportMinDateAllow				= true
PendingBLHPVLedgerReportMinDate						= 01-04-2025

PendingDeliveryStockReportMinDateAllow				= false
PendingDeliveryStockReportMinDate					= 01-04-2025

DueDeliveredWayBillReportMinDateAllow				= false
DueDeliveredWayBillReportMinDate					= 01-04-2025

PendingDdmSettlementReportMinDateAllow				= false	
PendingDdmSettlementReportMinDate					= 01-04-2025


