GroupName	= Shree Sahajanand Logistics
GroupCode	= sst
GroupId		= 41


DefaultMinDate										= 01-12-2019

BookButNotDispatchReportMinDateAllow				= true
BookButNotDispatchReportMinDate						= 01-12-2019

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 01-12-2019

ToPayDoorGodownStockReportMinDateAllow				= true
ToPayDoorGodownStockReportMinDate					= 01-12-2019

GodownStockReportMinDateAllow						= true
GodownStockReportMinDate							= 01-12-2019

PartyWiseLRDetailsReportMinDateAllow				= true
PartyWiseLRDetailsReportMinDate						= 01-12-2019

PendingDispatchStockReportMinDateAllow				= true
PendingDispatchStockReportMinDate					= 01-12-2019

PendingBLHPVLedgerReportMinDateAllow				= true
PendingBLHPVLedgerReportMinDate						= 01-12-2019

PendingDeliveryStockReportMinDateAllow				= true
PendingDeliveryStockReportMinDate					= 01-12-2019

PendingDdmSettlementReportMinDateAllow				= true	
PendingDdmSettlementReportMinDate					= 01-12-2019

DueDeliveredWayBillReportMinDateAllow				= true
DueDeliveredWayBillReportMinDate					= 01-12-2019
