GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

DefaultMinDate										= 09-12-2018
MinDateToViewOldData								= 01-04-2014

BookButNotDispatchReportMinDateAllow				= true
BookButNotDispatchReportMinDate						= 09-12-2018

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 09-12-2018

ToPayDoorGodownStockReportMinDateAllow				= true
ToPayDoorGodownStockReportMinDate					= 09-12-2018

GodownStockReportMinDateAllow						= true
GodownStockReportMinDate							= 09-12-2018

PartyWiseLRDetailsReportMinDateAllow				= true
PartyWiseLRDetailsReportMinDate						= 09-12-2018

PendingDispatchStockReportMinDateAllow				= true
PendingDispatchStockReportMinDate					= 09-12-2018

PendingBLHPVLedgerReportMinDateAllow				= true
PendingBLHPVLedgerReportMinDate						= 09-12-2018

PendingDeliveryStockReportMinDateAllow				= true
PendingDeliveryStockReportMinDate					= 09-12-2018

DueDeliveredWayBillReportMinDateAllow				= true
DueDeliveredWayBillReportMinDate					= 09-12-2018

PendingDdmSettlementReportMinDateAllow				= true	
PendingDdmSettlementReportMinDate					= 09-12-2018