GroupName	= Southern Tourist
GroupCode	= Southern
GroupId		= 6

DefaultMinDate							= 01-01-2001

PendingDeliveryStockReportMinDateAllow			= true
PendingDeliveryStockReportMinDate				= 01-01-2021