GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

DefaultMinDate										= 01-04-2025
MinDateToViewOldData								= 01-04-2025

BookButNotDispatchReportMinDateAllow				= true
BookButNotDispatchReportMinDate						= 01-04-2025

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 01-04-2025

ToPayDoorGodownStockReportMinDateAllow				= true
ToPayDoorGodownStockReportMinDate					= 01-04-2025

GodownStockReportMinDateAllow						= true
GodownStockReportMinDate							= 01-04-2025

PartyWiseLRDetailsReportMinDateAllow				= true
PartyWiseLRDetailsReportMinDate						= 01-04-2025

PendingDispatchStockReportMinDateAllow				= true
PendingDispatchStockReportMinDate					= 01-04-2025

PendingBLHPVLedgerReportMinDateAllow				= true
PendingBLHPVLedgerReportMinDate						= 01-04-2025

PendingDeliveryStockReportMinDateAllow				= true
PendingDeliveryStockReportMinDate					= 01-04-2025

DueDeliveredWayBillReportMinDateAllow				= true
DueDeliveredWayBillReportMinDate					= 01-04-2025

PendingDdmSettlementReportMinDateAllow				= true	
PendingDdmSettlementReportMinDate					= 01-04-2025

UnbilledRegisterCreditorWiseReportMinDateAllow		= true
UnbilledRegisterCreditorWiseReportMinDate			= 01-04-2025