GroupName	= Parshwanath Travel Agency
GroupCode	= PTA
GroupId		= 8

DefaultMinDate										= 01-12-2018

BookButNotDispatchReportMinDateAllow				= true
BookButNotDispatchReportMinDate						= 01-12-2018

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 01-12-2018

ToPayDoorGodownStockReportMinDateAllow				= true
ToPayDoorGodownStockReportMinDate					= 01-12-2018

GodownStockReportMinDateAllow						= true
GodownStockReportMinDate							= 01-12-2018

PartyWiseLRDetailsReportMinDateAllow				= true
PartyWiseLRDetailsReportMinDate						= 01-12-2018

PendingDispatchStockReportMinDateAllow				= true
PendingDispatchStockReportMinDate					= 01-12-2018

PendingBLHPVLedgerReportMinDateAllow				= true
PendingBLHPVLedgerReportMinDate						= 01-12-2018

PendingDeliveryStockReportMinDateAllow				= true
PendingDeliveryStockReportMinDate					= 01-12-2018

PendingDdmSettlementReportMinDateAllow				= true	
PendingDdmSettlementReportMinDate					= 01-12-2018

DueDeliveredWayBillReportMinDateAllow				= true
DueDeliveredWayBillReportMinDate					= 01-12-2018
