GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= ACCOUNT_GROUP_CODE
GroupId		= ACCOUNT_GROUP_ID

DefaultMinDate										= 01-04-2016
MinDateToViewOldData								= 01-04-2014

BookButNotDispatchReportMinDateAllow				= false
BookButNotDispatchReportMinDate						= 01-04-2016

LoadingSheetWithoutLHPVReportMinDateAllow			= true
LoadingSheetWithoutLHPVReportMinDate				= 01-04-2020

ToPayDoorGodownStockReportMinDateAllow				= false
ToPayDoorGodownStockReportMinDate					= 01-04-2016

GodownStockReportMinDateAllow						= false
GodownStockReportMinDate							= 01-04-2016

PartyWiseLRDetailsReportMinDateAllow				= false
PartyWiseLRDetailsReportMinDate						= 01-04-2016

PendingDispatchStockReportMinDateAllow				= false
PendingDispatchStockReportMinDate					= 01-04-2016

PendingBLHPVLedgerReportMinDateAllow				= false
PendingBLHPVLedgerReportMinDate						= 01-04-2016

PendingDeliveryStockReportMinDateAllow				= false
PendingDeliveryStockReportMinDate					= 01-04-2016

DueDeliveredWayBillReportMinDateAllow				= false
DueDeliveredWayBillReportMinDate					= 01-04-2016

PendingDdmSettlementReportMinDateAllow				= false	
PendingDdmSettlementReportMinDate					= 01-04-2016

UnbilledRegisterCreditorWiseReportMinDateAllow		= false
UnbilledRegisterCreditorWiseReportMinDate			= 01-04-2016

DueBillCreditorWiseReportMinDateAllow				= false
DueBillCreditorWiseReportMinDate					= 01-04-2024

noOfDaysToViewData									= 0

UnbilledRegisterReportMinDateAllow					= false
UnbilledRegisterReportMinDate						= 01-04-2016

firstDateToCompare									= 30-04_01-04
secondDateToCompare									= 31-10_01-10
allowCustomMinDate									= false