
GroupName	= ACCOUNT_GROUP_NAME
GroupCode	= 000

#Region_Name			= id

RegionIdsForSourceBranches			= 0

#Subregion_Name			= id

SubregionIdsForSourceBranches		= 0
SubregionIdsForDestBranches			= 0

### Normal_TBB 
#Charge For  Source subregion branches to Dest subregion branches
Normal_Tbb				= 0

### Crossing 
# Source region branches to dest subregion branches
SourceRegionBranchesToDestSubregionBranches		= 0
# Any crossing agent to Dest subregion branches
AnyCrossingAgentToDestSubregionBranches			= 0